name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    env:
      work_path: build_${{ matrix.os }}
      dist_path: dist_${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Pillow PySide6 patch pyinstaller
    - name: Build an executable
      run: |
        pyinstaller --clean --workpath '${{ env.work_path }}' --distpath '${{ env.dist_path }}' PSEPSX.spec
    - name: Upload an artifact
      uses: actions/upload-artifact@v3
      with:
        name: PSEPSX-${{ runner.os }}
        path: ${{ env.dist_path }}/*
    - name: Create the development build archive
      run: |
        cd ${{ env.dist_path }}
        7z a PSEPSX.zip PSEPSX.exe
        cd ..
      if: runner.os == 'Windows'
    - name: Release the development build
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: latest
        prerelease: true
        title: Development Build
        files: ${{ env.dist_path }}/PSEPSX.zip
      if: runner.os == 'Windows'
